Updating docs
kjohnson3595/TextAttackHMC22-23 pull request #9
Opened 2022-11-30 04:01 UTC by jlucassen

Adds one paragraph to the readme explaining how to use various commands. Also linted, which changed some files besides the readme.

2022-11-30 04:36 UTC, kjohnson3595 approved these changes

2022-12-01 01:40 UTC, nanakonoda approved these changes
Looks good!

2022-12-01 09:26 UTC, nanakonoda requested changes
Should be python -m eukaryote interactive...?

2022-12-02 06:36 UTC, nanakonoda approved these changes

2022-12-02 18:53 UTC, merged